export enum Categories {
    Vlogs = "Vlogs",
    TechReviews = "Tech Reviews",
    Gaming = "Gaming",
    EducationTutorials = "Education & Tutorials",
    DIYCrafts = "DIY & Crafts",
    FitnessHealth = "Fitness & Health",
    FoodCooking = "Food & Cooking",
    BeautyFashion = "Beauty & Fashion",
    MotivationSelfImprovement = "Motivation & Self-Improvement",
    MusicCovers = "Music & Covers",
    MovieTVReviews = "Movie & TV Show Reviews",
    ScienceTechnology = "Science & Technology",
    FinanceBusiness = "Finance & Business",
    ComedySkits = "Comedy & Skits",
    PranksChallenges = "Pranks & Challenges",
    TravelAdventure = "Travel & Adventure",
    ASMRRelaxation = "ASMR & Relaxation",
    CarAutomotive = "Car & Automotive",
    UnboxingHauls = "Unboxing & Hauls",
    StorytellingPodcasting = "Storytelling & Podcasting",
  }